Controllers/CarroController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Rocastone.Data;
using Rocastone.Models;
using Rocastone.Models.ViewModels;
using Rocastone.Utilidades;
using System.Security.Claims;
using System.Text;

namespace Rocastone.Controllers
{
    [Authorize] //solo puede ver losproductos que agrego el usuario si se loguea
    public class CarroController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHost; //para utilizar templates
        private readonly IEmailSender _emailSender;

        public CarroController(ApplicationDbContext context, IWebHostEnvironment webHost, IEmailSender emailSender)
        {
            _context = context;
            _webHost = webHost;
            _emailSender = emailSender;
        }

        //Get
        public IActionResult Index() //Obtengo la vista del carro de compras al hacer click sobre él
        {
            List<CarroCompras> carroCompraList = new List<CarroCompras>(); //Creo una lista de compras de productos obteniendo  Id del producto

            if (HttpContext.Session.GetObject<IEnumerable<CarroCompras>>(WebConstantes.SessionCarroCompras) != null &&
                HttpContext.Session.GetObject<IEnumerable<CarroCompras>>(WebConstantes.SessionCarroCompras).Count() > 0)
            {
                carroCompraList = HttpContext.Session.GetObject<List<CarroCompras>>(WebConstantes.SessionCarroCompras);
            }

            List<int> prodEnCarro = carroCompraList.Select(c => c.ProductoId).ToList();
            IEnumerable<Producto> prodList = _context.Productos.Where(p => prodEnCarro.Contains(p.Id));

            return View(prodList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]

        public IActionResult IndexPost() //Obtengo la vista del carro de compras al hacer click sobre él
        {
            return RedirectToAction("Resumen");
        }

        //GET
        public IActionResult Resumen()
        {
            //Traer al usuario conectado de la siguiente manera
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //Traigo los datos de la session
            List<CarroCompras> carroCompraList = new List<CarroCompras>(); //Creo una lista de compras de productos obteniendo  Id del producto

            if (HttpContext.Session.GetObject<IEnumerable<CarroCompras>>(WebConstantes.SessionCarroCompras) != null &&
                HttpContext.Session.GetObject<IEnumerable<CarroCompras>>(WebConstantes.SessionCarroCompras).Count() > 0)
            {
                carroCompraList = HttpContext.Session.GetObject<List<CarroCompras>>(WebConstantes.SessionCarroCompras);
            }

            List<int> prodEnCarro = carroCompraList.Select(c => c.ProductoId).ToList();
            IEnumerable<Producto> prodList = _context.Productos.Where(p => prodEnCarro.Contains(p.Id));

            //Traigo los datos de usuario
            ProductoUsuarioViewModel productoUsuario = new ProductoUsuarioViewModel()
            {
                ApplicationUser = _context.Usuarios.FirstOrDefault(u => u.Id == claim.Value),
                ProductoLista = prodList,
            };
            return View(productoUsuario);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Resumen")]

        public async Task<IActionResult> ResumenPost(ProductoUsuarioViewModel productoUsuarioVM)
        {
            //Traigo el template del wwwroot que sera la plantilla que me llegara por mail cuando el usuario haga la orden
            var rutaTemplate = _webHost.WebRootPath + Path.DirectorySeparatorChar.ToString()
                                 + "templates" + Path.DirectorySeparatorChar.ToString()
                                 + "PlantillaOrden.html";

            var subject = "Nueva orden";
            string HtmlBody = "";

            //Abro el template y lo leo
            using (StreamReader sr = System.IO.File.OpenText(rutaTemplate))
            {
                HtmlBody = sr.ReadToEnd();
            }

            StringBuilder productoListaSB = new StringBuilder();
            foreach (var prod in productoUsuarioVM.ProductoLista)
            {
                //Creo Html en el foreach con el .Append
                productoListaSB.Append($" - Nombre: { prod.Nombre } <span style='font-size:14px;'> (ID: { prod.Id })</span><br />");

                string MessageBody = string.Format(HtmlBody, productoUsuarioVM.ApplicationUser.Nombre,
                    productoUsuarioVM.ApplicationUser.Apellido,
                    productoUsuarioVM.ApplicationUser.Email,
                    productoUsuarioVM.ApplicationUser.Telefono,
                    productoUsuarioVM.ApplicationUser.Provincia,
                    productoUsuarioVM.ApplicationUser.Ciudad,
                    productoUsuarioVM.ApplicationUser.Direccion,
                    productoUsuarioVM.ApplicationUser.CodigoPostal,
                    productoListaSB.ToString());
                await _emailSender.SendEmailAsync(WebConstantes.EmailAdmin, subject, MessageBody);
            }

            return RedirectToAction(nameof(Confirmacion));
        }

        public IActionResult Confirmacion()
        {
            HttpContext.Session.Clear(); //Limpio la session para quitar los productos del carro de compras al enviar la orden.
            return View();
        }

        //Metodo para eliminar los productos del carro
        public async Task<IActionResult> Remover(int id)
        {
            List<CarroCompras> carroCompraList = new List<CarroCompras>(); //Creo una lista de compras de productos obteniendo el id del producto agregado

            if (HttpContext.Session.GetObject<IEnumerable<CarroCompras>>(WebConstantes.SessionCarroCompras) != null &&
                HttpContext.Session.GetObject<IEnumerable<CarroCompras>>(WebConstantes.SessionCarroCompras).Count() > 0)
            {
                carroCompraList = HttpContext.Session.GetObject<List<CarroCompras>>(WebConstantes.SessionCarroCompras);
            }

            carroCompraList.Remove(carroCompraList.FirstOrDefault(p => p.ProductoId == id));
            HttpContext.Session.SetObject(WebConstantes.SessionCarroCompras, carroCompraList); //Actualizo el carro
            return RedirectToAction("Index");
        }
    }
}

Controllers/ProductosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rocastone.Data;
using Rocastone.Models;
using Rocastone.Models.ViewModels;


namespace Rocastone.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment; //PARA EL MANEJO DE IMAGENES

        public ProductosController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Producto> lista = await _context.Productos.Include(c => c.Categoria).Include(t => t.TipoAplicacion).ToListAsync();
            return View(lista);

        }


        //GET UPSERT
        public async Task<IActionResult> Upsert(int? id)
        {
            //instancio el objeto  ProductoViewModel productoVM ya  que trabajare con objetos de varios modelos dif.
            ProductoViewModel productoVM = new ProductoViewModel()
            {
                Producto = new Producto(),
                CategoriaLista = _context.Categorias.Select(c => new SelectListItem
                {
                    Text = c.NombreCategoria,
                    Value = c.Id.ToString()
                }),
                TipoAplicacionLista = _context.TiposAplicaciones.Select(c => new SelectListItem
                {
                    Text = c.Nombre,
                    Value = c.Id.ToString()
                })
            };

            if (id == null)
            {
                // Crear nuevo producto... se activa el asp-action="Upsert" que no tiene id porque lo llamo desde el boton crear nuevo producto

                return View(productoVM);
            }
            else //si el objeto trae un id se activa el boton de actualizar
            {
                // Actualizar el producto... se activa el asp-route-id=@item.Id="Upsert" porque lo llamo desde el boton actualizar producto

                productoVM.Producto = await _context.Productos.FindAsync(id);
                if (productoVM.Producto == null)
                {
                    return NotFound();
                }
                return View(productoVM);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(ProductoViewModel productoViewModel)
        {
            if (ModelState.IsValid)
            {
                //variables para capturar las imagenes que los usuarios elijan 
                var files = HttpContext.Request.Form.Files;
                string webRootPath = _webHostEnvironment.WebRootPath;

                if (productoViewModel.Producto.Id == 0)
                {
                    //CREAR
                    string upload = webRootPath + WebConstantes.ImagenRuta; //ruta local donde guardare las imagenes
                    string fileName = Guid.NewGuid().ToString(); //Se le asigna un ID Guid a la img que se grabara
                    string extension = Path.GetExtension(files[0].FileName); //se obtiene el tipo de extension (png,jpg) del archivo

                    using (FileStream fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    productoViewModel.Producto.imgUrl = fileName + extension;
                    await _context.Productos.AddAsync(productoViewModel.Producto);
                }
                else
                {
                    // ACTUALIZAR
                    Producto objProducto = await _context.Productos.AsNoTracking().FirstOrDefaultAsync(p => p.Id == productoViewModel.Producto.Id);
                    if (files.Count > 0)//el usuario carga una nueva imagen
                    {
                        string upload = webRootPath + WebConstantes.ImagenRuta; //ruta local donde guardare las imagenes
                        string fileName = Guid.NewGuid().ToString(); //Se le asigna un ID Guid a la img que se grabara
                        string extension = Path.GetExtension(files[0].FileName);

                        //ahora se borrara la imagen anterior y se cargara la  nueva
                        var anteriorFile = Path.Combine(upload, objProducto.imgUrl);
                        if (System.IO.File.Exists(anteriorFile))//buscamos que la imagen este en nuestro directorio guardada
                        {
                            System.IO.File.Delete(anteriorFile); //procedemos a borrar la foto anterior del directorio
                        }
                        //fin borrar imagen anterior

                        using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }
                        productoViewModel.Producto.imgUrl = fileName + extension;
                    }
                    else //si cambia cualquier dato y deja la foto que tenía entonces lo de abajo
                    {
                        productoViewModel.Producto.imgUrl = objProducto.imgUrl;
                    }
                    _context.Productos.Update(productoViewModel.Producto);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //Se llenan nuevamente las listas por si algo falla
            productoViewModel.CategoriaLista = _context.Categorias.Select(c => new SelectListItem
            {
                Text = c.NombreCategoria,
                Value = c.Id.ToString()
            });
            productoViewModel.TipoAplicacionLista = _context.TiposAplicaciones.Select(c => new SelectListItem
            {
                Text = c.Nombre,
                Value = c.Id.ToString()
            });

            return View(productoViewModel);
        }


        //GET
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Producto producto = await _context.Productos.Include(c => c.Categoria)
                                                        .Include(t => t.TipoAplicacion)
                                                        .FirstOrDefaultAsync(p => p.Id == id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(Producto producto)
        {
            if (producto == null)
            {
                return NotFound();
            }
            // Eliminar la imagen
            string upload = _webHostEnvironment.WebRootPath + WebConstantes.ImagenRuta;

            // borrar la imagen anterior
            var anteriorFile = Path.Combine(upload, producto.imgUrl);
            if (System.IO.File.Exists(anteriorFile))
            {
                System.IO.File.Delete(anteriorFile);
            }
            // fin Borrar imagen anterior

            _context.Productos.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



    }
}

Views/Shared/_Layout.cshtml
@using Rocastone.Utilidades
@inject IHttpContextAccessor HttpContextAccesor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rocastone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sandstone.min.css" />
    <link rel="stylesheet" href="~/Rocastone.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rocastone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        @if (User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Administrar Contenido
                                </a>
                                <ul class="dropdown-menu" caria-labelledby="navbarDropdown">
                                    <li class="">
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="UserRoles" asp-action="Index">Administracion de Roles</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categoría</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="TipoAplicaciones" asp-action="Index">Aplicaciones</a>
                                    </li>
                                </ul>
                            </li>
                        }

                        <li>
                            @if (HttpContextAccesor.HttpContext.Session.GetObject<List<CarroCompras>>(WebConstantes.SessionCarroCompras) != null)
                            {
                                <a asp-action="Index" asp-controller="Carro" class="nav-link">
                                    @{
                                        var count = HttpContextAccesor.HttpContext.Session.GetObject<List<CarroCompras>>(WebConstantes.SessionCarroCompras).Count();
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            }
                            else
                            {
                                <a href="#" class="nav-link">  <i class="fas fa-shopping-cart"></i> &nbsp; (0) </a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container mb-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Rocastone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ProductoCard.cshtml
@model Rocastone.Models.Producto


<div class="col-lg-4 col-md-6 pb-4 filter @Model.Categoria.NombreCategoria.Replace(' ','_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7">
                <label class="float-left text-dark">@Model.Nombre</label>
            </div>
            <div class="col-5">
                <label class="float-right">
                    <span class="text-info h5">@Model.Precio</span> / m &sup2;
                </label>
            </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WebConstantes.ImagenRuta/@Model.imgUrl" alt="Imagen Card">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Categoria.NombreCategoria</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100 text-dark" style="background-color:aliceblue">@Model.TipoAplicacion.Nombre</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.ShortDescripcion</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Detalle" asp-route-Id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">Ver Detalle</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
    <partial name="_ValidationScriptsPartial" />
 }

}