Models/Categoria.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Rocastone.Models
{
    [Index(nameof(NombreCategoria), IsUnique = true)]
    public class Categoria
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Categoría")]
        [Required(ErrorMessage = "El campo {0} es obligatorio")] //data Notation.. Required es como un Not Null
        [MaxLength(50, ErrorMessage = "El campo {0} debe tener máximo {1} carácteres")]

        public string? NombreCategoria { get; set; }


        [Display(Name = "Nro. de orden")]
        [Required(ErrorMessage = "En número de orden es requerido")]
        [Range(1, int.MaxValue, ErrorMessage = "El orden debe ser mayor a cero")]
        public int MostrarOrden { get; set; }
    }
}

Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rocastone.Data;
using Rocastone.Models;

namespace Rocastone.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriasController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Categoria> lista = await _context.Categorias.ToListAsync();
            return View(lista);
        }

        //Get
        public async Task<IActionResult> Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Categoria categoria)
        {
            //_context.Categorias.Add(categoria);
            //_context.SaveChanges();
            //return RedirectToAction("Index");

            if (ModelState.IsValid) //if (ModelState.IsValid) significa que cumpla con todos los data notations
            {
                //creo un try catch para evitar que se registren dos categorias con el mismo nombre
                try
                {
                    await _context.Categorias.AddAsync(categoria);
                    await _context.SaveChangesAsync(); //para grabar los datos, el await espera al submit
                    return RedirectToAction(nameof(Index));
                }

                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe una categoría con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }

                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }
            return View(categoria); //me retorna a la vista categoria por si me quedo algun dato por llenar que no me vacie el form
        }

        //GET
        public async Task<IActionResult> Editar(int? id)
        {
            //Carlo la lista de categorias buscando sus Ids
            if (id == null || _context.Categorias == null)
            {
                return NotFound();
            }

            Categoria categoria = await _context.Categorias.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, Categoria categoria)
        {
            if (id != categoria.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Categorias.Update(categoria);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index), new { id });

                }
                catch (DbUpdateException dbUpdateException)
                {

                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe una categoría con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }

            }
            return View(categoria);
        }


        //GET
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.Categorias == null)
            {
                return NotFound();
            }
            Categoria categoria = await _context.Categorias.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int? id, Categoria categoria)
        {
            if (categoria == null || id == null)
            {
                return NotFound();
            }
            _context.Categorias.Remove(categoria);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

Views/Categorias/Crear.cshtml
@model Rocastone.Models.Categoria
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Crear">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="p-3">
        <div class="form-group row">
            <h2 class="text-primary">Crear nueva Categoria</h2>

            <div class="container">
                <div class="row">
                    <div class="col-md-6 mb-2">
                        <label asp-for="NombreCategoria" class="form-label fw-bold"></label>
                        <input asp-for="NombreCategoria" class="form-control" />
                        <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-md-6">
                        <label asp-for="MostrarOrden" class="form-label fw-bold"></label>
                        <input asp-for="MostrarOrden" class="form-control" />
                        <span asp-validation-for="MostrarOrden" class="text-danger"></span>
                    </div>
                </div>

                <button type="submit" class="btn btn-outline-primary me-1">Crear</button>
                <a class="btn btn-outline-success" asp-controller="Categorias" asp-action="Index">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
}

    }

Views/Categorias/Editar.cshtml
@model Rocastone.Models.Categoria
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form method="post" asp-action="Editar">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="p-3">
        <div class="form-group row">
            <h2 class="text-primary">Editar Categoría</h2>

            <div class="container">
                <div class="row">
                    <div class="col-md-6 mb-2">
                        <label asp-for="NombreCategoria" class="form-label fw-bold"></label>
                        <input asp-for="NombreCategoria" class="form-control" />
                        <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-md-6">
                        <label asp-for="MostrarOrden" class="form-label fw-bold"></label>
                        <input asp-for="MostrarOrden" class="form-control" />
                        <span asp-validation-for="MostrarOrden" class="text-danger"></span>
                    </div>
                </div>

                <button type="submit" class="btn btn-outline-primary me-1">Editar</button>
                <a class="btn btn-outline-success" asp-controller="Categorias" asp-action="Index">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
}

    }

Views/Categorias/Eliminar.cshtml
@model Rocastone.Models.Categoria
@{
    ViewData["Title"] = "Eliminar";
}

<form method="post" asp-action="Eliminar">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="p-3">
        <div class="form-group row">
            <h2 class="text-danger">¿Desea eliminar Categoría?</h2>

            <div class="container">
                <div class="row">
                    <div class="col-md-6 ">
                        <label asp-for="NombreCategoria" class="form-label fw-bold"></label>
                        <input asp-for="NombreCategoria" disabled class="form-control" />
                        <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mt-3 mb-3">
                    <div class="col-md-6">
                        <label asp-for="MostrarOrden" class="form-label fw-bold"></label>
                        <input asp-for="MostrarOrden" disabled class="form-control" />
                        <span asp-validation-for="MostrarOrden" class="text-danger"></span>
                    </div>
                </div>

                <button type="submit" class="btn btn-outline-danger me-1">Eliminar</button>
                <a class="btn btn-outline-success" asp-controller="Categorias" asp-action="Index">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
}

    }

Views/Categorias/Index.cshtml
@model IEnumerable<Rocastone.Models.Categoria>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />

<div class="container">
    <h1 class="text-warning">Categorías</h1>
    <div class="row">
        <div class="col-md-8">
            <h2 class="text-primary">Lista de Categorias</h2>
        </div>
        <div></div>
        <div class=col-md-6>
            <div>
                <a asp-controller="Categorias" asp-action="Crear" class="btn btn-success mt-2 mb-4 "><i class="fa-solid fa-plus"></i> Crear nueva categoría</a>
            </div>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-md-8">
            @if (Model.Count() > 0)
            {
                <table class="table table-light table-striped table-bordered" id="MyTable">
                    <thead>
                        <tr>
                            @* <th class="text-center"> @Html.DisplayNameFor(model => model.Id)</th>*@
                            <th class="text-center text-secondary"> @Html.DisplayNameFor(model => model.NombreCategoria)</th>
                            <th class="text-center text-secondary"> @Html.DisplayNameFor(model => model.MostrarOrden)</th>
                            <th class="text-center text-secondary">Editar/Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                @*<th class="text-center">  @Html.DisplayFor(modelItem => item.Id)</th>*@
                                <th class="text-center">@Html.DisplayFor(modelItem => item.NombreCategoria)</th>
                                <th class="text-center"> @Html.DisplayFor(modelItem => item.MostrarOrden)</th>
                                <th class="text-center">
                                    <div role="group">
                                        <a asp-controller="Categorias" asp-action="Editar" asp-route-id=@item.Id class="btn btn-outline-primary mx-1"><i class="fa-solid fa-pen"></i> Editar</a>
                                        <a asp-controller="Categorias" asp-action="Eliminar" asp-route-id=@item.Id class="btn btn-outline-danger mx-1"><i class="fa-solid fa-trash"></i> Eliminar</a>
                                    </div>
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>

@section Scripts {
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}


<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
    $('#MyTable').DataTable({
    "language": {
    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
    },
    "aLengthMenu": [
    [10,25, 50, 100, 200, -1],
    [10,25, 50, 100, 200, "Todos"]
    ]
    });
    });
</script>
}